[package]
name = "crack"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
regex = "1.10.2"
serde = { version = "1.0.192", features = ["derive"] }
toml = "0.8.8"

[lints.clippy]
pedantic = "warn"

[dev-dependencies]
tempfile = "3.8.1"
